"""Email delivery for meeting plans — Gmail (WhatsApp) + Graph sendMail (Teams)."""

from __future__ import annotations

import html
import re
from typing import Any

from agent.config import settings
from agent.core.channel_identity import is_teams_session
from agent.core.logging import get_logger
from agent.services import gmail, ms_graph

logger = get_logger(__name__)

_EMAIL_RE = re.compile(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}")


def parse_recipients(message: str) -> list[str]:
    found = _EMAIL_RE.findall(message or "")
    out: list[str] = []
    seen: set[str] = set()
    for addr in found:
        key = addr.lower()
        if key not in seen:
            seen.add(key)
            out.append(addr)
    return out


def build_plan_email_html(
    *,
    plan: dict[str, Any],
    published: dict[str, Any],
    executive_summary: str = "",
) -> str:
    title = html.escape(published.get("title") or plan.get("title") or "Meeting Plan")
    summary = html.escape(executive_summary or plan.get("executive_summary") or "")
    md = published.get("md_url") or ""
    docx = published.get("docx_url") or ""
    links = []
    if md:
        links.append(f'<li><a href="{html.escape(md)}">Markdown plan</a></li>')
    if docx:
        links.append(f'<li><a href="{html.escape(docx)}">DOCX plan</a></li>')
    link_block = "<ul>" + "".join(links) + "</ul>" if links else "<p><em>Links unavailable</em></p>"
    return (
        f"<h2>{title}</h2>"
        f"<p>{summary}</p>"
        f"<h3>Published artifacts</h3>{link_block}"
        f"<p><em>Generated by Meeting Intelligence Fabric</em></p>"
    )


async def send_plan_email(
    *,
    recipients: list[str],
    subject: str,
    body_html: str,
    teams_user_id: str = "",
) -> dict[str, Any]:
    if not recipients:
        raise ValueError("At least one recipient email is required")
    if not settings.enable_meeting_plan_email:
        return {"status": "skipped", "reason": "ENABLE_MEETING_PLAN_EMAIL=false"}

    sent: list[str] = []
    errors: list[str] = []

    if teams_user_id and is_teams_session(f"teams:{teams_user_id}"):
        try:
            await _graph_send_mail(
                user_id=teams_user_id,
                to=recipients,
                subject=subject,
                body_html=body_html,
            )
            sent.extend(recipients)
        except Exception as exc:
            logger.exception("Graph sendMail failed")
            errors.append(str(exc))
    else:
        for addr in recipients:
            try:
                gmail.send_email(addr, subject, body_html)
                sent.append(addr)
            except Exception as exc:
                logger.exception("Gmail send failed for %s", addr)
                errors.append(f"{addr}: {exc}")

    if not sent:
        raise RuntimeError("; ".join(errors) or "Email send failed")
    return {"status": "sent", "recipients": sent, "errors": errors}


async def _graph_send_mail(
    *,
    user_id: str,
    to: list[str],
    subject: str,
    body_html: str,
) -> None:
    if not ms_graph.graph_configured():
        raise RuntimeError("Graph not configured for Teams email")
    payload = {
        "message": {
            "subject": subject,
            "body": {"contentType": "HTML", "content": body_html},
            "toRecipients": [{"emailAddress": {"address": addr}} for addr in to],
        },
        "saveToSentItems": True,
    }
    await ms_graph.graph_request("POST", f"/users/{user_id}/sendMail", json_body=payload)
