"""Documentation Agent — publish release notes to SharePoint (Graph).

Feature: Release Agent Fabric. No-op / clear message when ENABLE_DOCS_AGENT is false.

Publishing strategy (most reliable first):
1. Enrich from Azure DevOps PR (commits, files, comments) + LLM draft
2. Upload HTML file to the site Documents library under /ReleaseNotes/
3. Fall back to Site Pages API when available
"""

from __future__ import annotations

import html
import re
from datetime import datetime, timezone
from typing import Any
from urllib.parse import quote

import httpx

from agent.agents.state import AgentState
from agent.config import settings
from agent.core.logging import get_logger
from agent.models.release_event import (
    STATUS_DOCS_PUBLISHED,
    find_release_event,
    upsert_release_event,
)
from agent.services import ms_graph
from agent.services.release_notes_builder import build_release_notes_document

logger = get_logger(__name__)

AGENT_NAME = "docs_agent"

_PR_RE = re.compile(r"\b(?:pr|pull\s*request)\s*#?\s*(\d+)\b", re.I)
_PIPELINE_RE = re.compile(r"\b(?:pipeline|build)\s*#?\s*(\d+)\b", re.I)
_RELEASE_RE = re.compile(r"\b(rel_[a-f0-9]+)\b", re.I)


def _extract_ids(message: str) -> dict[str, str | None]:
    text = message or ""
    pr = _PR_RE.search(text)
    pipe = _PIPELINE_RE.search(text)
    rel = _RELEASE_RE.search(text)
    return {
        "pr_id": pr.group(1) if pr else None,
        "pipeline_id": pipe.group(1) if pipe else None,
        "release_id": rel.group(1) if rel else None,
    }


def _page_html(event: dict[str, Any], title: str) -> str:
    """Minimal fallback when no PR id is available."""
    artifacts = event.get("artifacts") or []
    art_lines = "".join(
        f"<li>{html.escape(str(a.get('type', 'artifact')))}: "
        f"{html.escape(str(a.get('url', '')))}</li>"
        for a in artifacts
        if isinstance(a, dict)
    )
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{html.escape(title)}</title>
<style>
body {{ font-family: Segoe UI, Arial, sans-serif; margin: 2rem; color: #242424; }}
h1 {{ color: #0f6cbd; }}
table {{ border-collapse: collapse; margin: 1rem 0; }}
td, th {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
th {{ background: #f5f5f5; }}
</style></head>
<body>
<h1>{html.escape(title)}</h1>
<table>
<tr><th>Release ID</th><td>{html.escape(str(event.get('release_id') or ''))}</td></tr>
<tr><th>PR</th><td>{html.escape(str(event.get('pr_id') or 'n/a'))}</td></tr>
<tr><th>Pipeline</th><td>{html.escape(str(event.get('pipeline_id') or 'n/a'))}</td></tr>
<tr><th>Build</th><td>{html.escape(str(event.get('build_id') or 'n/a'))}</td></tr>
<tr><th>Commit</th><td>{html.escape(str(event.get('commit_sha') or 'n/a'))}</td></tr>
<tr><th>Environment</th><td>{html.escape(str(event.get('env') or ''))}</td></tr>
<tr><th>App URL</th><td>{html.escape(str(event.get('app_url') or 'n/a'))}</td></tr>
<tr><th>QA report</th><td>{html.escape(str(event.get('qa_report_url') or 'pending'))}</td></tr>
</table>
<h2>Summary</h2>
<p>{html.escape(str(event.get('summary') or 'Automated release notes from Release Agent Fabric.'))}</p>
<h2>Artifacts</h2>
<ul>{art_lines or '<li>None yet</li>'}</ul>
<p><em>Generated by Documentation Agent · Sunny Personal AI Agent ·
{html.escape(datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC'))}</em></p>
</body></html>"""


async def resolve_site_id() -> tuple[str, str]:
    """Return (site_id, web_url)."""
    site_id = (settings.ms_graph_sharepoint_site_id or "").strip()
    if site_id:
        site = await ms_graph.graph_request("GET", f"/sites/{site_id}")
        return site["id"], site.get("webUrl") or ""

    host = (settings.ms_graph_sharepoint_hostname or "").strip()
    path = (settings.ms_graph_sharepoint_site_path or "").strip()
    if not host or not path:
        raise RuntimeError(
            "Set MS_GRAPH_SHAREPOINT_SITE_ID or "
            "MS_GRAPH_SHAREPOINT_HOSTNAME + MS_GRAPH_SHAREPOINT_SITE_PATH"
        )
    if not path.startswith("/"):
        path = "/" + path
    site = await ms_graph.graph_request("GET", f"/sites/{host}:{path}")
    return site["id"], site.get("webUrl") or ""


async def _upload_html_to_drive(
    *,
    site_id: str,
    title: str,
    html_body: str,
) -> dict[str, Any]:
    """Upload release notes HTML into Documents/ReleaseNotes (reliable Graph path)."""
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    safe = re.sub(r"[^A-Za-z0-9_-]+", "-", title)[:60].strip("-") or "release-notes"
    filename = f"{safe}-{stamp}.html"
    try:
        await ms_graph.graph_request(
            "POST",
            f"/sites/{site_id}/drive/root/children",
            json_body={
                "name": "ReleaseNotes",
                "folder": {},
                "@microsoft.graph.conflictBehavior": "fail",
            },
        )
    except Exception:
        logger.info("ReleaseNotes folder may already exist")

    token = await ms_graph.get_app_token()
    path = quote(f"/ReleaseNotes/{filename}", safe="/")
    url = f"https://graph.microsoft.com/v1.0/sites/{site_id}/drive/root:{path}:/content"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "text/html; charset=utf-8",
    }
    async with httpx.AsyncClient(timeout=60.0) as client:
        resp = await client.put(url, headers=headers, content=html_body.encode("utf-8"))
        if resp.status_code >= 400:
            logger.error("Drive upload failed %s %s", resp.status_code, resp.text[:500])
            resp.raise_for_status()
        item = resp.json()

    return {
        "page_id": item.get("id"),
        "web_url": item.get("webUrl") or "",
        "site_id": site_id,
        "method": "drive_html",
        "filename": filename,
    }


async def create_sharepoint_release_page(
    *,
    title: str,
    event: dict[str, Any],
    html_body: str | None = None,
) -> dict[str, Any]:
    """Create release notes in SharePoint (drive upload primary, site page fallback)."""
    site_id, site_web = await resolve_site_id()
    body = html_body or _page_html(event, title)

    try:
        result = await _upload_html_to_drive(site_id=site_id, title=title, html_body=body)
        result["html_preview"] = body
        result["site_web"] = site_web
        return result
    except Exception:
        logger.exception("Drive upload failed — trying Site Pages API")

    safe_name = re.sub(r"[^A-Za-z0-9_-]+", "-", title)[:80].strip("-") or "release-notes"
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    page = await ms_graph.graph_request(
        "POST",
        f"/sites/{site_id}/pages",
        json_body={
            "@odata.type": "#microsoft.graph.sitePage",
            "name": f"{safe_name}-{stamp}.aspx",
            "title": title,
            "pageLayout": "article",
        },
    )
    page_id = page.get("id")
    web_url = page.get("webUrl") or site_web
    try:
        await ms_graph.graph_request(
            "POST",
            f"/sites/{site_id}/pages/{page_id}/microsoft.graph.sitePage/publish",
        )
    except Exception:
        logger.exception("SharePoint publish step failed page=%s", page_id)

    return {
        "page_id": page_id,
        "web_url": web_url,
        "site_id": site_id,
        "method": "site_page",
        "html_preview": body,
        "site_web": site_web,
    }


async def publish_release_notes(state: AgentState) -> AgentState:
    """LangGraph node entry — safe when feature disabled."""
    if not settings.enable_docs_agent:
        return {
            **state,
            "status": "skipped",
            "handled_by": AGENT_NAME,
            "notification_text": (
                "*Documentation Agent* is installed but **disabled** "
                "(ENABLE_DOCS_AGENT=false).\n\n"
                "Ask your admin to enable it after Graph credentials are set. "
                "Existing Dev / WhatsApp flows are unchanged."
            ),
        }

    if not ms_graph.docs_agent_ready():
        return {
            **state,
            "status": "failed",
            "handled_by": AGENT_NAME,
            "notification_text": (
                "*Documentation Agent* is enabled but Microsoft Graph is not configured.\n"
                "Set MS_GRAPH_TENANT_ID, MS_GRAPH_CLIENT_ID, MS_GRAPH_CLIENT_SECRET "
                "and SharePoint site settings. See docs/RELEASE_AGENT_FABRIC_GRAPH_SETUP.md"
            ),
        }

    msg = state.get("user_message") or ""
    ids = _extract_ids(msg)
    pr_id = ids.get("pr_id") or (str(state.get("pr_number")) if state.get("pr_number") else None)

    event = None
    if ids.get("release_id"):
        from agent.models.release_event import get_release_event

        event = await get_release_event(str(ids["release_id"]))
    if event is None:
        event = await find_release_event(
            pr_id=pr_id,
            pipeline_id=ids.get("pipeline_id"),
            build_id=state.get("ci_build_id"),
        )

    if event is None:
        if not pr_id and not ids.get("pipeline_id") and not ids.get("release_id"):
            return {
                **state,
                "status": "failed",
                "handled_by": AGENT_NAME,
                "notification_text": (
                    "*Documentation Agent* — release notes need a **PR or release id**.\n\n"
                    "Examples:\n"
                    "• *write release notes for PR 51*\n"
                    "• *write release notes for rel_abc123*\n\n"
                    "To **create a general document** (report, brief, memo), say:\n"
                    "• *prepare a document about …* or *create report on …*\n\n"
                    "_I will not replay a cached release note without an explicit PR/release id._"
                ),
            }
        title = f"Release notes — PR {pr_id or 'manual'}"
        event = await upsert_release_event(
            pr_id=pr_id,
            pipeline_id=ids.get("pipeline_id"),
            commit_sha=state.get("commit_sha"),
            app_url=settings.agent_app_url,
            status=STATUS_DOCS_PUBLISHED,
            requested_by=state.get("whatsapp_phone"),
            channel="teams" if str(state.get("whatsapp_phone") or "").startswith("teams:") else "whatsapp",
            title=title,
            summary=msg[:2000],
        )
    else:
        title = event.get("title") or f"Release notes — PR {event.get('pr_id') or event.get('release_id')}"

    html_body: str | None = None
    evidence: dict[str, Any] = {}
    sections: dict[str, Any] = {}
    enrich_note = ""

    if pr_id:
        try:
            title, html_body, evidence, sections = await build_release_notes_document(
                pr_id=pr_id,
                event=event,
                project=state.get("azdo_project") or settings.azdo_demo_project,
                repo_name=state.get("repo_name") or settings.azdo_demo_repo,
                repo_id=state.get("azdo_repo_id"),
            )
            event = await upsert_release_event(
                release_id=event["release_id"],
                pr_id=pr_id,
                commit_sha=evidence.get("commit_sha") or event.get("commit_sha"),
                title=title,
                summary=str(sections.get("executive_summary") or "")[:4000],
                app_url=settings.agent_app_url,
                extra={
                    "pr_url": evidence.get("pr_url"),
                    "repo_name": evidence.get("repo_name"),
                    "file_count": evidence.get("file_count"),
                },
            )
            enrich_note = (
                f"*Repo:* {evidence.get('repo_name')} · "
                f"*Files:* {evidence.get('file_count')} · "
                f"*Commits:* {len(evidence.get('commits') or [])}\n"
            )
        except Exception as exc:
            logger.exception("PR enrichment failed for PR %s — publishing basic notes", pr_id)
            enrich_note = (
                f"_Warning: could not fully load AzDO PR #{pr_id} ({exc}). "
                "Published a basic template; retry after confirming AZDO_PAT access._\n"
            )

    try:
        result = await create_sharepoint_release_page(
            title=title, event=event, html_body=html_body
        )
        doc_url = result.get("web_url") or ""
        updated = await upsert_release_event(
            release_id=event["release_id"],
            status=STATUS_DOCS_PUBLISHED,
            doc_url=doc_url,
            title=title,
            summary=event.get("summary") or (sections.get("executive_summary") if sections else msg[:2000]),
            extra={"publish_method": result.get("method"), "filename": result.get("filename")},
        )
        note = (
            f"*Documentation Agent* — enterprise release notes published.\n\n"
            f"*Release:* `{updated['release_id']}`\n"
            f"*PR:* {updated.get('pr_id') or 'n/a'} · *Pipeline:* {updated.get('pipeline_id') or 'n/a'}\n"
            f"{enrich_note}"
            f"*Method:* {result.get('method')}\n"
        )
        if doc_url:
            note += f"*SharePoint:* {doc_url}\n"
        else:
            note += "_File created in Documents/ReleaseNotes — open the site library if URL is missing._\n"
        return {
            **state,
            "status": "completed",
            "handled_by": AGENT_NAME,
            "notification_text": note,
            "release_id": updated["release_id"],
            "doc_url": doc_url,
        }
    except Exception as exc:
        logger.exception("Docs agent failed")
        return {
            **state,
            "status": "failed",
            "handled_by": AGENT_NAME,
            "notification_text": (
                f"*Documentation Agent* failed: {exc}\n\n"
                "Checklist:\n"
                "1. API permission *Sites.ReadWrite.All* + **Admin consent**\n"
                "2. App settings MS_GRAPH_* on App Service\n"
                "3. Site path `/sites/EnterpriseProjectHub` exists\n"
                "4. AZDO_PAT can read the PR in Project-NIT\n"
            ),
            "error": str(exc),
        }
